### ISSUE TITLE
Auto refresh?

### ISSUE THREAD

**Issue by theronic** [duct-framework/core#12]
How can I refresh handlers without running `(reset)`?

**Comment by weavejester** [comment]
You should be able to use a file-watcher library like [Hawk](https://github.com/wkf/hawk) to run a function on file change. If someone gets that working and packages it up as a small function, I'd be okay with adding it to the `dev.clj` template file.

It's also worth noting that most Clojure editors allow for assigning a command to a keybinding, so for instance, I have a keybinding that automatically saves the file I'm working on, and then triggers a system reset at the REPL.

**Comment by weavejester** [comment]
Should be fixed in master.
