### ISSUE TITLE
Extract the module system

### ISSUE THREAD

**Issue by clyfe** [duct-framework/core#14]
:duct/module functionality should be :integrant/module and be implemented either in integrant or an intermediary project like integrant-module, as it has a level of generality beyond duct. And have it be in cljc.

**Comment by weavejester** [comment]
I'm considering it, but I don't want to put anything in Integrant until I have a stable API. You may have noticed that the module system has changed in the 0.11 alpha versions.

**Comment by clyfe** [comment]
Is the API stable yet? Would be nice to have this available in cljs.

**Comment by weavejester** [comment]
No, but we could always add cljs support to duct/core.

**Comment by clyfe** [comment]
I have boiled the module system to [this](https://gist.github.com/clyfe/6d281e166f46aa9122fadea71b4ab07f) duct.core extraction, in cljc form.
I'm considering publishing it to clojars, unless there's a more official plan for it.
Duct core could piggyback on it adding daemons and servers and whatnot.

**Comment by weavejester** [comment]
The Duct module system isn't stable yet, and will likely be changed in the next six months. You're free to separate out whatever you want from Duct, however.

**Comment by clyfe** [comment]
Forked here: https://github.com/tape-framework/module
Naming is changed from duct.core to tape.module.
It supports both Clojure & ClojureScript, however the functionality is reduced.
