### ISSUE TITLE
Data readers for `duct.core.merge`

### ISSUE THREAD

**Issue by g7s** [duct-framework/core#26]
Currently we cannot use `duct.core.merge` tagging (i.e. `merge/distinct`, `merge/displace` etc) on non `clojure.lang.IObj` values in an **edn** configuration. 

Is it possible to create data readers to do the tagging?

EDIT: I mean ofc we can pass our own data readers in `duct.core/read-config` but shouldn't Duct provide the readers by default?

**Comment by weavejester** [comment]
That's not a bad idea. I'd accept a PR for it.

**Comment by g7s** [comment]
Sure. Let me see what I can do

**Comment by weavejester** [comment]
Fixed by #27.
