### ISSUE TITLE
Stop the watcher after auto-reset

### ISSUE THREAD

**Issue by hden** [duct-framework/core#33]
The watcher created by `auto-reset` function will prevent the process from exiting. For example, when combined with rebel-readline, the watcher will prevent the repl from exiting even after the `:repl/quit` command.

It might be helpful if there is a helper for stopping the watcher or at least document it in case one might forget to turn it off.

```clojure
(let [watcher (auto-reset)]
  (hawk/stop! watcher))
```

**Comment by weavejester** [comment]
You'll need to explain your setup, since the default `lein repl` exits fine. I suspect this may be more an issue with your REPL setup than with `auto-reset`, as a REPL should still be able to exit even when there are background threads running.

**Comment by hden** [comment]
You are right. It seems that the rebel-readline library handles exit command a little differently. 

https://github.com/bhauman/rebel-readline/blob/1fc954215bc287ad590dac8e52c782d6077fee55/rebel-readline/src/rebel_readline/commands.clj#L181-L184

Maybe we can close this issue and open another for rebel-readline?

My deps.edn

```clojure
{:paths ["resources" "src"]

 :deps {com.cognitect/anomalies {:mvn/version "0.1.12"}
        com.cognitect/http-client {:mvn/version "0.1.104"}
        com.datomic/client-cloud {:mvn/version "0.8.83"}
        com.datomic/ion {:mvn/version "0.9.35"}
        duct/core {:mvn/version "0.8.0"}
        duct/module.ataraxy {:mvn/version "0.3.0"}
        duct/module.logging {:mvn/version "0.5.0"}
        duct/module.web {:mvn/version "0.7.0"
                         :exclusions [org.eclipse.jetty/jetty-server]}
        hden/duct.module.datomic {:mvn/version "0.1.0-SNAPSHOT"}
        org.eclipse.jetty/jetty-server {:mvn/version "9.4.24.v20191120"}}

 :mvn/repos {"datomic-cloud" {:url "s3://datomic-releases-1fc2183a/maven/releases"}}

 :aliases
 {;; Load the development environment.
  :dev {:extra-paths ["dev/resources" "dev/src"]
        :extra-deps {integrant/repl {:mvn/version "0.3.1"}
                     hawk {:mvn/version "0.2.11"}}}

  ;; Launch a REPL.
  :rebel {:extra-deps {com.bhauman/rebel-readline {:mvn/version "0.1.4"}}
          :main-opts  ["-m" "rebel-readline.main"]}

  ;; Test dependencies. Note that this does not invoke a runner.
  :test {:extra-paths ["test"]
         :extra-deps {eftest {:mvn/version "0.5.9"}
                      kerodon {:mvn/version "0.9.1"}}}

  ;; A test runner.
  :runner {:extra-deps {com.cognitect/test-runner
                        {:git/url "https://github.com/cognitect-labs/test-runner"
                         :sha "209b64504cb3bd3b99ecfec7937b358a879f55c1"}}
           :main-opts ["-m" "cognitect.test-runner" "-d" "test"]}}}
```

**Comment by weavejester** [comment]
Isn't this an issue with rebel-readline? This doesn't seem to be an issue specific to Duct, but one where rebel-readline can't exit if there are running background threads.

**Comment by hden** [comment]
You are right. Thanks for your time. Closing this issue.
