### ISSUE TITLE
Coerce env vars to keywords

### ISSUE THREAD

**Issue by arichiardi** [duct-framework/core#38]
Hi there, we have a couple of configuration options for XTDB that require us to pass strings that are then converted in keywords.
While it is fine to do this in our `init-key`, it would be great if we could add a `defmethod` in [this file](https://github.com/duct-framework/core/blob/master/src/duct/core/env.clj) for that.

Wanted to open the issue to understand if it makes sense, I could probably take care of it in case.

Thanks a lot for `duct`!

**Comment by weavejester** [comment]
So a coercion method to change a environment variable into a keyword? That sounds fine.

**Comment by arichiardi** [comment]
yeah, just calling `keyword` in the `defmethod` basically :smile:

**Comment by arichiardi** [comment]
@weavejester apologies for writing here but is a `duct` release planned soon-ish, I would love to try the new stuff out!

An alternative would be to add a `deps.edn` file so that our team can take the `git/sha` route :smile:
