### ISSUE TITLE
Allow duct/read-config to support custom data readers

### ISSUE THREAD

**Issue by RickMoynihan** [duct-framework/core#4]
It would be nice to be able to extend the set of data readers supplied to `duct/read-config`.

Due to the var-args on `read-config` its not possible to modify this function without breaking backwards compatibility, though we could define a different function `read-config*` that allows you to set the readers, without changing the behaviour of read-config.

**Comment by RickMoynihan** [comment]
Am I right that the 0.5.0 release fixes precisely this issue?

**Comment by weavejester** [comment]
Yes it does. I'll close this issue.

**Comment by RickMoynihan** [comment]
Brilliant 👍
