### ISSUE TITLE
[QUESTION]: why the medley dependency?

### ISSUE THREAD

**Issue by jimpil** [duct-framework/core#43]
Hi there,

I can see the `medley` dependency in the project.clj file, but I can't find where it's being used. `duct.core` is the only namespace that requires it, but it's not actually using it within! What am I missing? 

Thanks in advance...

**Comment by weavejester** [comment]
It looks like it was left over from a previous commit that removed the use of Medley, but not the dependency or require.

**Comment by jimpil** [comment]
I see - thanks for the clarification...do you have any plans of releasing a version w/o that dependency? 

Happy holidays :)

**Comment by jimpil** [comment]
hello?

**Comment by weavejester** [comment]
Hi, sorry for the delay; I've been away traveling. I'll release a version without that dependency this weekend.

**Comment by jimpil** [comment]
Nice one - thanks! :)

**Comment by jimpil** [comment]
sorry, I realised that I closed the issue prematurely the other day. Feel free to close this when you are ready :+1:

**Comment by zelark** [comment]
> Hi, sorry for the delay; I've been away traveling. I'll release a version without that dependency this weekend.

It'd be great! Cause now we get this warning
`WARNING: abs already refers to: #'clojure.core/abs in namespace: medley.core, being replaced by: #'medley.core/abs`

**Comment by jimpil** [comment]
I actually wouldn't mind the warning, if the dependency was meaningful and/or valuable.
