### ISSUE TITLE
The custom readers' tag cannot be used when the tag is behind a `:duct.core/include`

### ISSUE THREAD

**Issue by zerg000000** [duct-framework/core#5]
The `read-config` can take custom readers as second argument. However, the `duct.core/prep` has a separate call to `read-config` for evaluating the `edn` defined in `:duct.core/include`. Which means we have no way to define custom readers for reading config under key `:duct.core/include`.

**Comment by weavejester** [comment]
Good point. We either need to add the readers as an option to `prep`, or perhaps allow some global registration of data readers specific to Duct.
